### ISSUE TITLE
Slicer Linux dashboard issues

### ISSUE THREAD

**Issue by fedorov** [Radiomics/SlicerRadiomics#16] opened 2017-04-29 20:15 UTC
<s>Build on Win fails, but as discussed that is expected.</s>. See #20

Linux: cmake issues http://slicer.cdash.org/viewBuildError.php?buildid=1014261

![image](https://cloud.githubusercontent.com/assets/313942/25558538/ea01321c-2cf6-11e7-8fc4-e25ca82ed550.png)

@jcfr ?

**Comment by jcfr** [comment] 2017-05-30 15:33
The Linux issue persist. See http://slicer.cdash.org/viewBuildError.php?buildid=1033658

I wasn't able to reproduce it locally .. I will debug on the factory later this week

**Comment by fedorov** [comment] 2017-08-16 16:34
Different issue now: http://slicer.cdash.org/viewBuildError.php?buildid=1080469

**Comment by jcfr** [comment] 2017-09-06 20:16
The linux error occurs because on the factory, the script `/usr/bin/lsb_release` (used by `pip`) is written in python and despite of having `#!/usr/bin/python` at the top, the python library and environment that are used are the one of Slicer which is missing the package `lsb_release` ...

**Comment by jcfr** [comment] 2017-09-09 16:18
I will integrate and finalize the fix when I am back from vacation on the week of sept 19th.

**Comment by ihnorton** [comment] 2017-09-29 16:21
An alternative fix would be to edit `lsb_release` first line on the factory system and add `-Es`. That's what is done to avoid this issue in newer lsb/ubuntu releases:

https://bugs.launchpad.net/ubuntu/+source/lsb/+bug/938869/comments/28

**Comment by jcfr** [comment] 2017-09-29 17:06
@ihnorton  Thanks for the suggestion, when all distributions we build one will have implemented the use of `-Es` , we will remove the use of the `lsb_release` wrapper from Slicer.

In the mean time, I am closing this issue as I confirm build of extension complete on the Linux factory.

**Closed by jcfr** 2017-09-29 17:06 UTC
Labels: bug
