### ISSUE TITLE
Windows installation for Slicer Radiomics not working

### ISSUE THREAD

**Issue by JoostJM** [Radiomics/SlicerRadiomics#23] opened 2017-06-14 14:08 UTC
When installing SlicerRadiomics from extension manager, installation works, however, the module cannot be loaded due to an error with the pyYAML library. When you comment out `import pykwalify` in `featureextractor.py` (in the installed site-packages), module loads fine and works without issue (pykwalify not needed in slicer extension)

**Comment by pieper** [comment] 2017-06-19 12:29
See user discussion here: https://discourse.slicer.org/t/qunatitative-features-with-eeterogeneitycad/518/8

**Comment by pieper** [comment] 2017-07-15 14:24
@JoostJM was this issue fixed by [d0a77c](https://github.com/Radiomics/SlicerRadiomics/commit/d0a77cdef62b5345d36dc3a56370dd9574ba9bc8)?

**Comment by JoostJM** [comment] 2017-07-17 07:40
@pieper, d0a77c presents a temporary workaround. Additionally, that fix won't take effect until the extension is rebuilt and repackaged.

**Comment by fedorov** [comment] 2017-07-17 12:15
Joost, the extension is rebuilt and packaged automatically on each source code update.

**Comment by pieper** [comment] 2017-07-17 13:59
I just tested the current nightly build on windows (2017-07-16) and confirmed that the Radiomics extension is working as expected.  So the workaround is in place but the underlying issue remains.

**Comment by jcfr** [comment] 2017-09-29 21:58
Now #16 is fixed, I will address this next week.

**Comment by JoostJM** [comment] 2017-11-13 15:14
@jcfr, what is the status of this issue?

**Comment by jcfr** [comment] 2017-11-13 15:17
Thanks for the note. I will follow up later today or tomorrow.

**Comment by renjiliang** [comment] 2017-12-04 09:41
I have installed radiomics extension，but the following bug was always appeared. How to resolve the problem?

 File "C:/Users/Administrator/AppData/Roaming/NA-MIC/Extensions-26309/SlicerRadiomics/lib/Slicer-4.7/qt-scripted-modules/SlicerRadiomics.py", line 535, in run
    enabledImageTypes)
  File "C:/Users/Administrator/AppData/Roaming/NA-MIC/Extensions-26309/SlicerRadiomics/lib/Slicer-4.7/qt-scripted-modules/SlicerRadiomics.py", line 448, in calculateFeatures
    extractor.disableAllImagesTypes()

**Comment by renjiliang** [comment] 2017-12-04 09:47
I did not find import "pykwalify.core" in file featureextractor

**Comment by JoostJM** [comment] 2017-12-04 09:57
@renjiliang, That's correct, `pykwalify.core` is currently disabled due to this issue. We are working on a fix. The error you received is unrelated and due to a typo bug in the SlicerRadiomics Code. I corrected this just now in 8c4ffc7. This change will be incorporated in tonights nightly build of slicer, so to fix it, reinstall the latest nightly of slicer tomorrow, or apply the fix yourself in the `SlicerRadiomics` python file, which is located somewhere in `C:\Users\<USER>\AppData\Roaming\NA-MIC\Extensions-26442\SlicerRadiomics\Lib\Slicer-4.7\qt-scripted-modules` (It is possible that the extensions number is different, but the NA-MIC folder contains all your installed Slicer Extensions, including SlicerRadiomics).

**Comment by fedorov** [comment] 2017-12-08 15:57
It looks like now build is failing because a warning is interpreted as an error:

http://slicer.cdash.org/viewBuildError.php?buildid=1148769

```
  D:\D\N\Slicer-1-build\python-install\Lib\site-packages\pip\commands\install.py:194: UserWarning: 
  Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
```

**Comment by jcfr** [comment] 2017-12-08 16:43
Yes. 

I have been working on address this, it will be fixed later today.

**Comment by jcfr** [comment] 2017-12-09 19:10
Extension now available on all platform: http://slicer.cdash.org/index.php?project=Slicer4&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=Radiomics

After releasing Slicer 4.8.1, it will also be available with the stable release.

**Closed by jcfr** 2017-12-09 19:10 UTC
Labels: bug
